name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - name: Install
        run: cd ./blog-angular && npm install
      - name: Build
        # baseHref уже в angular.json, но можно продублировать для надёжности
        run: cd ./blog-angular && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog-angular/dist/blog-angular/browser
